### PR TITLE
Continuous integration

### PR DESCRIPTION
**Pull request by ossi-saukko**
Hello @Luni-4 ,

Could you look at these changes and make the necessary modifications or help me to do them?

Thank you.

### CODE REVIEW

**Comment by Luni-4** [comment]
Thank you @ossi-saukko! 

Below some changes to fix CI:

- If it's not a cross-platform project, remove Windows and MacOS scripts
- Run `cargo fmt` and `cargo clippy` on the entire code to fix lints
- Install https://github.com/sifis-home/wp4-edge_ids/blob/master/Dockerfile#L14 `libpcap` as a new step for each job, otherwise it's not possible to build the project
- Remove MacOS in the deployment script and do the step above for this script too

**Comment by ossi-saukko** [comment]
Any tips for running Clippy with the same settings as it is run in GitHub or how to get the usable output of the problems?
Test coverage is lacking and will be even worse as we are hurrying to get the program usable for integration.

Next, we are working on adding more features, but hopefully can continue with this in a few weeks.

**Comment by Luni-4** [comment]
Thank you for your work @ossi-saukko!

About `clippy`, this is the command: `cargo clippy --all-targets --tests --benches -- -D warnings`

About code coverage job, you can comment `Get total coverage` and `Evaluate code coverage` steps until more tests will be added

**Comment by ossi-saukko** [comment]
Thank you. That is a good idea.

**Comment by Luni-4** [comment]
Sorry, you can just comment `Get total coverage` and `Evaluate code coverage` steps, the rest of the job can be not commented, in this way you can see your percentage of coverage

**Review by Luni-4 — APPROVED** [review]
It's fine for me, you can merge it! Perhaps squash the commits first

Thanks for your work @ossi-saukko!

**Comment by ossi-saukko** [comment]
Thank you, @Luni-4. 

I have learned a lot of exciting things about Rust and GitHub.

**Pull request merged**
